import { useEffect, useState } from 'react'
import { api } from '../api/client'
import type { BriefingInfo } from '../api/types'

function fmtSize(bytes: number): string {
  return bytes > 1024 * 1024 ? `${(bytes / (1024 * 1024)).toFixed(1)} MB` : `${Math.round(bytes / 1024)} KB`
}

export default function Briefings() {
  const [briefings, setBriefings] = useState<BriefingInfo[]>([])
  const [scripts, setScripts] = useState<Record<string, string>>({})
  const [openScript, setOpenScript] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    api
      .getBriefings()
      .then(setBriefings)
      .catch((e) => setError(e instanceof Error ? e.message : 'Failed to load'))
      .finally(() => setLoading(false))
  }, [])

  async function toggleScript(day: string) {
    if (openScript === day) {
      setOpenScript(null)
      return
    }
    setOpenScript(day)
    if (!scripts[day]) {
      try {
        const { script } = await api.getBriefingScript(day)
        setScripts((s) => ({ ...s, [day]: script }))
      } catch {
        setScripts((s) => ({ ...s, [day]: '(script unavailable)' }))
      }
    }
  }

  if (loading) return <div className="text-gray-500">Loading...</div>
  if (error) return <div className="text-red-500">Error: {error}</div>

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold text-gray-900">Audio Briefings</h1>
      <p className="text-sm text-gray-500">
        The spoken daily digest generated by TTS and attached to each newsletter.
      </p>

      {briefings.length === 0 ? (
        <div className="text-gray-500">No briefings generated yet.</div>
      ) : (
        <div className="space-y-3">
          {briefings.map((b) => (
            <div key={b.date} className="bg-white shadow rounded-lg p-4">
              <div className="flex flex-wrap items-center gap-4">
                <span className="text-sm font-semibold text-gray-900 w-28">
                  {new Date(b.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}
                </span>
                <audio
                  controls
                  preload="none"
                  className="h-9 grow min-w-64"
                  src={`/api/v1/briefings/${b.date}/audio`}
                />
                <span className="text-xs text-gray-400">{fmtSize(b.size_bytes)}</span>
                {b.has_script && (
                  <button
                    onClick={() => toggleScript(b.date)}
                    className="text-sm font-medium text-blue-600 hover:text-blue-800"
                  >
                    {openScript === b.date ? 'Hide script' : 'Script'}
                  </button>
                )}
              </div>
              {openScript === b.date && (
                <pre className="mt-3 p-3 bg-gray-50 rounded text-sm text-gray-700 whitespace-pre-wrap font-sans max-h-72 overflow-y-auto">
                  {scripts[b.date] ?? 'Loading…'}
                </pre>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
